// <auto-generated />
namespace Cinema_Ticketing_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class hm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hm));
        
        string IMigrationMetadata.Id
        {
            get { return "201805110930474_hm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
